repos:
    -   repo: meta
        hooks:
            -   id: check-hooks-apply
            -   id: check-useless-excludes

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.0.1
        hooks:
            -   id: check-merge-conflict
            -   id: check-yaml
            -   id: end-of-file-fixer
                exclude: .svg$
            -   id: trailing-whitespace
                exclude: (?x)(
                    .md$|
                    .svg$
                    )
            -   id: file-contents-sorter
                files: |
                    (?x)(
                      requirements.txt|
                      .gitignore
                    )

    -   repo: https://github.com/PyCQA/isort
        rev: 5.10.1
        hooks:
            -   id: isort
                args: [ "--profile", "black", "-p", "config" ]

    -   repo: https://github.com/psf/black
        rev: 21.12b0
        hooks:
            -   id: black
                args: [ "--line-length", "88", "--target-version", "py310" ]

    -   repo: https://github.com/codespell-project/codespell
        rev: v2.1.0
        hooks:
            -   id: codespell
                exclude: tests/fixtures/python.svg

    -   repo: https://github.com/PyCQA/flake8
        rev: 4.0.1
        hooks:
            -   id: flake8
                additional_dependencies:
                    - flake8-blind-except
                    - flake8-bugbear
                    - flake8-comprehensions
                    - flake8-debugger
                    - flake8-docstrings
                    - flake8-logging-format
                    - flake8-print
                    - flake8-pytest-style
                    - flake8-tidy-imports

    -   repo: https://github.com/PyCQA/bandit
        rev: 1.7.1
        hooks:
            -   id: bandit
                args: [ "-l", "-v", "-c", ".bandit.yaml" ]
