[package]
name = "{{ project_name }}"
version = "0.1.0"
description = "A Mojo Package"
authors = ["{{ author_name }} <{{ author_email }}>"]
license = ""
repository = ""
edition = "2023"
mojo-version = "0.6.1"

################################################################

# workspace
[workspace]
members = [
    # add your workspace members here
]

exclude = [
    # exclude your workspace members here
    #    "tmp",
]



################################################################

# Binary target settings.
[[bin]]
name = "mojoapp"
path = "src/main.mojo"

# Library target settings.
[lib]
name = "mojolib"           # The name of the target.
path = "src/lib.mojo"    # The source file of the target.
type = "mojopkg"        # The type of the target.


################################################################
[replace]
"foo:0.1.0" = { git = 'https://github.com/example/foo.git' }
"bar:1.0.2" = { path = 'my/local/bar' }

# deps
[dependencies]

# build
[build-dependencies]
tauri-build = { version = "2.0.0-alpha.6", features = [] }
example-package = { version = "0.1.0", git = "https://github.com/example/example-package" }


[dev-dependencies]
example-package = { version = "0.1.0", git = "https://github.com/example/example-package" }



serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

################################################################

[python]
package-manager = "poetry"

