version: "3"

output: group # = [interleaved, group, prefixed] # ref:

vars:
  VAR1: "some-var"
  SRC_DIR: "src"

# global env:
env:
  ENV1: testing


################################################################################################

tasks:
  run:
    aliases: [ "r" ]
    cmds:
      - mojo run main.mojo
    dir: src/

  setup:
    cmds:
      - pip install mod-cli
      - mod --help

  mojo:
    aliases: [ "m" ]
    cmds:
      - mojo {{ '{{' }}.CLI_ARGS{{ '}}'}}

  poetry:
    aliases: [ "p" ]
    cmds:
      - poetry {{ '{{' }}.CLI_ARGS{{ '}}'}} # install, update, shell

  mod:
    aliases: [ "dep" ]
    cmds:
      - mod {{ '{{' }}.CLI_ARGS{{ '}}'}}

  new:
    aliases: [ "n" ]
    cmds:
      - mod new {{ '{{' }}.CLI_ARGS{{ '}}'}}

  # usage: -- loguru "typer[all]"
  add:
    aliases: [ "a" ]
    cmds:
      - mod add {{ '{{' }}.CLI_ARGS{{ '}}'}} # --dev

  help:
    aliases: [ "h" ]
    cmds:
      - mod --help
