version: "3"

output: group # = [interleaved, group, prefixed] # ref:

vars:
  VAR1: "some-var"
  SRC_DIR: "src/mod_cli"

# global env:
env:
  ENV1: testing


################################################################################################

tasks:
  run:
    aliases: [ "r" ]
    cmds:
      - echo "{{.SRC_DIR}}"
      - poetry run python3 main.py --help
      - poetry run python3 main.py -n Jim
    dir: src/mod_cli

  run:all:
    aliases: [ "ra" ]
    cmds:
      - echo "{{.SRC_DIR}}"
      - poetry run python3 main.py
      - poetry run python3 main.py --help
      - poetry run python3 main.py --name Bob
      - poetry run python3 main.py -n Jim
    dir: src/mod_cli

  dev:
    cmds:
      - poetry shell

  install:
    aliases: [ "i" ]
    cmds:
      - poetry install

  build:
    aliases: [ "b" ]
    cmds:
      - poetry build # ref: https://typer.tiangolo.com/tutorial/package/#create-a-wheel-package


  ################################################################################################


  # usage: -- loguru "typer[all]"
  add:
    aliases: [ "a" ]
    cmds:
      - poetry add {{.CLI_ARGS}}

  add:all:
    cmds:
      - poetry add "typer[all]" loguru
      - poetry add tomlkit rich

  remove:
    cmds:
      - poetry remove {{.CLI_ARGS}}

  info:
    cmds:
      - task: env
      - poetry debug info

  env:
    - poetry env info
    - poetry env list

  help:
    cmds:
      - poetry --help
      - poetry list
      - poetry env info


  config:
    aliases:
      - "cfg"
    cmds:
      - poetry config virtualenvs.options.no-setuptools false

  debug:
    cmds:
      - poetry config --help
      - poetry config --list
