version: "3"

output: group # = [interleaved, group, prefixed] # ref:

vars:
  VAR1: "some-var"
  SRC_DIR: "src/mod_cli"

# global env:
env:
  ENV1: testing


################################################################################################

tasks:
  run:
    aliases: [ "r" ]
    cmds:
      - echo "{{.SRC_DIR}}"
      - poetry run python3 main.py --help
      - poetry run python3 main.py {{.CLI_ARGS}}
    dir: src/mod_cli

  run:all:
    aliases: [ "ra" ]
    cmds:
      - echo "{{.SRC_DIR}}"
      - poetry run python3 main.py
      - poetry run python3 main.py --help
      - poetry run python3 main.py --name Bob
      - poetry run python3 main.py -n Jim
    dir: src/mod_cli

  poetry:
    aliases: [ "p" ]
    cmds:
      - poetry {{.CLI_ARGS}} # install, update, shell

  mod:
    aliases: [ "dep" ]
    cmds:
      - mod {{.CLI_ARGS}}

  install:
    aliases: [ "i" ]
    cmds:
      - poetry install

  build:
    aliases: [ "b" ]
    cmds:
      - poetry build # ref: https://typer.tiangolo.com/tutorial/package/#create-a-wheel-package


  ################################################################################################


  # usage: -- loguru "typer[all]"
  add:
    aliases: [ "a" ]
    cmds:
      - poetry add {{.CLI_ARGS}} # --dev

  add:all:
    cmds:
      - poetry add "typer[all]" loguru
      - poetry add tomlkit rich

  remove:
    cmds:
      - poetry remove {{.CLI_ARGS}}

  help:
    cmds:
      - poetry --help
      - poetry list
      - poetry env info

  rel:init:
    cmds:
      - echo ${PYPI_TOKEN}
      - poetry config pypi-token.pypi ${PYPI_TOKEN}

  rel:
    cmds:
      - echo ${PYPI_TOKEN}
      - poetry publish --build --dry-run
      - poetry publish --build

  rel:check:
    aliases: [ 'rc' ]
    cmds:
      - open https://pypi.org/project/mod-cli/
      - pip install mod-cli
